language: node_js
sudo: false
node_js:
    - 10
    - 12
    - 14
    - 16
    - 17
notifications:
    email:
        - andris@kreata.ee
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/0ed18fd9b3e529b3c2cc
        on_success: change # options: [always|never|change] default: always
        on_failure: always # options: [always|never|change] default: always
        on_start: false # default: false
